apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo-data-pvc
  namespace: kubeflow
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce