apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
type: Opaque
data:
  username: YWRtaW4K
  password: U29uIW5zOTgxNAo=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console-svc
spec:
  selector:
    app: minio
  ports:
  - port: 9001
    targetPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        args:
          - server
          - --address
          - 0.0.0.0:9000
          - --console-address
          - 0.0.0.0:9001
          - /storage
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9001
          hostPort: 9001
        volumeMounts:
          - mountPath: /storage
            name: storage
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio-creds
                key: username
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio-creds
                key: password
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc
            
