apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeflow-ingress
  namespace: kubeflow
  labels:
    name: kubeflow-ingress
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
  - host: kubeflow.k8s.sonins.co.kr
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ml-pipeline-ui
            port: 
              number: 3000